export { default as usuariosRouter } from './usuarios'
export { default as plantasRouter } from './plantas'
export { default as ventasRouter } from './ventas'
export { default as detallesVentaRouter } from './detallesVenta'
export { default as abonasRouter } from './abonos'
export { default as pagosVentaRouter } from './pagosVenta'